beauty_salon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('salon.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

salon/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeListView.as_view(), name='home'),
    path('about/', views.AboutListView.as_view(), name='about'),
    path('service/', views.ServiceListView.as_view(), name='service'),
    path('gallery/', views.GalleryListView.as_view(), name='gallery'),
    path('contact-us/', views.ContactUsView.as_view(), name='contact-us'),
]

salon/models.py
"""Create your models here."""
from django.db import models
from django.contrib.auth.models import User

from ckeditor_uploader.fields import RichTextUploadingField

GENDER_CHOICES =( 
    ("female", "female"),
    ("male", "male"),
)

CONTENT_CHOICES =( 
    ("about", "about"),
    ("service", "service"),
    ("contact", "contact"),
    ("footer", "footer"),
)

class TimeStampedModel(models.Model):
    """TimeStampedModel.
    An abstract base class model that provides self-managed "created" and
    "updated" fields.
    """

    created_on = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    modified_on = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        get_latest_by = 'modified_on'
        ordering = ('-modified_on', '-created_on',)
        abstract = True


class Slider(TimeStampedModel):
    """Slider model."""

    topic = models.CharField(max_length=50, null=True, blank=True)
    sub_topic = models.CharField(max_length=50, null=True, blank=True)
    discription = RichTextUploadingField(null=True, blank=True)
    image = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.topic

    class Meta:
        verbose_name_plural = "Slider"


class Service(TimeStampedModel):
    """Service model."""

    topic = models.CharField(max_length=50, null=True, blank=True)
    discription = RichTextUploadingField(null=True, blank=True)
    price = models.FloatField(null=True, blank=True)
    image = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.topic

    class Meta:
        verbose_name_plural = "Service"


class Category(TimeStampedModel):
    """Category model."""

    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Category"


class Gallery(TimeStampedModel):
    """Gallery model."""

    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    topic = models.CharField(max_length=255, null=True, blank=True)
    discription = RichTextUploadingField(null=True, blank=True)
    image = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.topic

    class Meta:
        verbose_name_plural = "Gallery"


class CompanyInfo(TimeStampedModel):
    """CompanyInfo model."""

    address = models.CharField(max_length=254, null=True, blank=True)
    phone_number = models.CharField(max_length=254, null=True, blank=True)
    email = models.EmailField(max_length=254, null=True, blank=True)
    fb = models.URLField(max_length=200, null=True, blank=True)
    twitter = models.URLField(max_length=200, null=True, blank=True)
    google = models.URLField(max_length=200, null=True, blank=True)
    pinterest = models.URLField(max_length=200, null=True, blank=True)
    discription = RichTextUploadingField(null=True, blank=True)
    timing = models.CharField(max_length=254, null=True, blank=True)
    company_name = models.CharField(max_length=254, null=True, blank=True)
    logo = models.FileField(null=True, blank=True)
    slogan = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.company_name or '-'

    class Meta:
        verbose_name_plural = "CompanyInfo"


class AboutUs(TimeStampedModel):
    """AboutUs model."""

    topic = models.CharField(max_length=255, null=True, blank=True)
    discription = RichTextUploadingField(null=True, blank=True)
    discription2 = RichTextUploadingField(null=True, blank=True)
    image = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.discription

    class Meta:
        verbose_name_plural = "AboutUs"


class Passion(TimeStampedModel):
    """Passion model."""

    topic = models.CharField(max_length=255, null=True, blank=True)
    discription = RichTextUploadingField(null=True, blank=True)

    def __str__(self):
        return self.topic

    class Meta:
        verbose_name_plural = "Passion"


class ContactUs(TimeStampedModel):
    """ContactUs model."""

    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    phone_number = models.CharField(max_length=254, null=True, blank=True)
    address = models.CharField(max_length=254, null=True, blank=True)
    message = RichTextUploadingField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "ContactUs"

class Content(TimeStampedModel):
    """Content model."""

    name = models.CharField(choices=CONTENT_CHOICES, max_length=200, null=True, blank=True)
    discription = RichTextUploadingField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Content"


class Facilities(TimeStampedModel):
    """ParlorFacilities model."""

    gender = models.CharField(choices=GENDER_CHOICES, max_length=200, null=True, blank=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    price = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Facilities"

templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
		
		<title>Beauty Salon | About Us</title>
		<!-- Loading third party fonts -->
		<link href="{% static 'fonts/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
		<link href="{% static 'fonts/novecento-font/novecento-font.css' %}" rel="stylesheet" type="text/css">
		<!-- Loading main css file -->
		<link rel="stylesheet" href="{% static 'style.css' %}">
		
		<!--[if lt IE 9]>
		<script src="js/ie-support/html5.js"></script>
		<script src="js/ie-support/respond.js"></script>
		<![endif]-->

	</head>


	<body>

		<div id="site-content">
			
			<header class="site-header">
				<div class="container">
					<a id="branding" href="{% url 'home' %}">
						{% if company_info.logo %}
							<img src={{company_info.logo.url}} alt="Company name" class="logo" height="50" width="50">
						{% else %}
							<img src="{% static 'images/logo.png' %}" alt="Company name" class="logo">
						{% endif %}
						<div class="logo-copy">
							<h1 class="site-title">{{company_info.company_name}}</h1>
							<small class="site-description">{{company_info.slogan}}</small>
						</div>
					</a> <!-- #branding -->

					
					<!-- Default snippet for navigation -->
					<div class="main-navigation">
						<button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
						<ul class="menu">
							<li class="menu-item"><a href="{% url 'home' %}">Home</a></li>
							<li class="menu-item current-menu-item"><a href="{% url 'about' %}">About</a></li>
							<li class="menu-item"><a href="{% url 'service' %}">Services</a></li>
							<li class="menu-item"><a href="{% url 'gallery' %}">Gallery</a></li>
							<li class="menu-item"><a href="{% url 'contact-us' %}">Contact</a></li>
						</ul> <!-- .menu -->
					</div> <!-- .main-navigation -->

					<div class="mobile-navigation"></div>
				</div>
			</header>

			<main class="main-content">
				<div class="page">
					<div class="container">
						<p>{{content.discription|safe}}</p>

						<div class="row">
							<div class="col-md-6">
								<h3 class="section-title">About</h3>
								<figure><img src="{{aboutus.image.url}}" alt=""></figure>
								<h4>{{aboutus.topic}}</h4>
								<p>{{aboutus.discription|safe}}</p>
								<p>{{aboutus.discription2|safe}}</p>
							</div>
							<div class="col-md-6">
								<h3 class="section-title">Passion</h3>
								{% for passion in passion_list %}
									<h4>{{passion.topic}}</h4>
									<p>{{passion.discription|safe}}</p>
								{% endfor %}
							</div>
							
						</div>
					</div>
				</div>
			</main>

			<footer class="site-footer">
				<div class="container">
					<div class="row">
						<div class="col-md-3">
							<div class="widget contact-widget">
								<h3 class="widget-title">Contact</h3>
								<div class="contact-info">
									<address>
										<img src="{% static 'images/icon-map-small.png' %}" class="icon">
										<p><strong>{{company_info.company_name}}</strong>{{company_info.address}}</p>
									</address>
									<a href="mailto:{{company_info.email}}" class="mail"><img src="{% static 'images/icon-envelope-small.png' %}" class="icon">{{company_info.email}}</a>
									<a href="tel:{{company_info.phone_number}}" class="phone"><img src="{% static 'images/icon-phone-small.png' %}" class="icon">{{company_info.phone_number}}</a>
								</div>
							</div>
						</div>
						<div class="col-md-3">
							<div class="widget">
								<h3 class="widget-title">Social Media</h3>
								<div class="social-links">
									<a href={{company_info.fb}} target="_blank"><i class="fa fa-facebook"></i></a>
									<a href={{company_info.twitter}} target="_blank"><i class="fa fa-twitter"></i></a>
									<a href={{company_info.google}} target="_blank"><i class="fa fa-google-plus"></i></a>
									<a href={{company_info.pinterest}} target="_blank"><i class="fa fa-pinterest"></i></a>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="widget">
								<h3 class="widget-title">Newsletter</h3>
								<p>{{company_info.discription|safe}} </p>
							</div>
						</div>
					</div>

					<div class="colophon">
						<p>{{footer_info.discription|safe}}</p>
					</div>
				</div>
			</footer>
		</div>
		

		

		<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
		<script src="{% static 'js/plugins.js' %}"></script>
		<script src="{% static 'js/app.js' %}"></script>
		
	</body>

</html>

templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
		
		<title>Beauty Salon</title>
		<!-- Loading third party fonts -->
		<link href="{% static 'fonts/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
		<link href="{% static 'fonts/novecento-font/novecento-font.css' %}" rel="stylesheet" type="text/css">
		<!-- Loading main css file -->
		<link rel="stylesheet" href="{% static 'style.css' %}">
		
		<!--[if lt IE 9]>
		<script src="js/ie-support/html5.js"></script>
		<script src="js/ie-support/respond.js"></script>
		<![endif]-->

	</head>


	<body>

		<div id="site-content">
			
			<header class="site-header">
				<div class="container">
					<a id="branding" href="{% url 'home' %}">
						{% if company_info.logo %}
							<img src={{company_info.logo.url}} alt="Company name" class="logo" height="50" width="50">
						{% else %}
							<img src="{% static 'images/logo.png' %}" alt="Company name" class="logo">
						{% endif %}
						<div class="logo-copy">
							<h1 class="site-title">{{company_info.company_name}}</h1>
							<small class="site-description">{{company_info.slogan}}</small>
						</div>
					</a> <!-- #branding -->

					
					<!-- Default snippet for navigation -->
					<div class="main-navigation">
						<button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
						<ul class="menu">
							<li class="menu-item"><a href="{% url 'home' %}">Home</a></li>
							<li class="menu-item"><a href="{% url 'about' %}">About</a></li>
							<li class="menu-item"><a href="{% url 'service' %}">Services</a></li>
							<li class="menu-item"><a href="{% url 'gallery' %}">Gallery</a></li>
							<li class="menu-item current-menu-item"><a href="{% url 'contact-us' %}">Contact</a></li>
						</ul> <!-- .menu -->
					</div> <!-- .main-navigation -->

					<div class="mobile-navigation"></div>
				</div>
			</header>

			<main class="main-content">
				<div class="page">
					<div class="container">
						<p>{{content.discription|safe}}</p>

						<div class="row">
							<div class="col-md-5">
								
								<form action="." method="post" class="contact-form" enctype="multipart/form-data">
									{% csrf_token %}
									<input type="text" id="id_name" name="name" placeholder="Name...">
									<input type="text" id="id_email" name="email" placeholder="Email...">
									<input type="text" id="id_phone_number" name="phone_number" placeholder="phone number...">
									<input type="text" id="id_address" name="address" placeholder="address...">
									<textarea id="id_message" name="message" placeholder="Message..."></textarea>
									<div class="text-right">
										<button class="button large" type="submit">Send Message</button>
									</div>
								</form>
							</div>
							<div class="col-md-6 col-md-offset-1">
								<div class="map-container">
									<div class="map"></div>
									<div class="address-info">
										<address>
											<img src="{% static 'images/icon-map-small.png' %}" class="icon">
											<p><strong>{{company_info.company_name}}</strong>{{company_info.address}}</p>
										</address>
										<div class="contact-info">
											<a href="mailto:{{company_info.email}}" class="mail"><img src="{% static 'images/icon-envelope-small.png' %}" class="icon">{{company_info.email}}</a>
											<a href="tel:{{company_info.phone_number}}" class="phone"><img src="{% static 'images/icon-phone-small.png' %}" class="icon">{{company_info.phone_number}}</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</main>

			<footer class="site-footer">
				<div class="container">
					<div class="row">
						<div class="col-md-3">
							<div class="widget contact-widget">
								<h3 class="widget-title">Contact</h3>
								<div class="contact-info">
									<address>
										<img src="{% static 'images/icon-map-small.png' %}" class="icon">
										<p><strong>{{company_info.company_name}}</strong>{{company_info.address}}</p>
									</address>
									<a href="mailto:{{company_info.email}}" class="mail"><img src="{% static 'images/icon-envelope-small.png' %}" class="icon">{{company_info.email}}</a>
									<a href="tel:{{company_info.phone_number}}" class="phone"><img src="{% static 'images/icon-phone-small.png' %}" class="icon">{{company_info.phone_number}}</a>
								</div>
							</div>
						</div>
						<div class="col-md-3">
							<div class="widget">
								<h3 class="widget-title">Social Media</h3>
								<div class="social-links">
									<a href={{company_info.fb}} target="_blank"><i class="fa fa-facebook"></i></a>
									<a href={{company_info.twitter}} target="_blank"><i class="fa fa-twitter"></i></a>
									<a href={{company_info.google}} target="_blank"><i class="fa fa-google-plus"></i></a>
									<a href={{company_info.pinterest}} target="_blank"><i class="fa fa-pinterest"></i></a>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="widget">
								<h3 class="widget-title">Newsletter</h3>
								<p>{{company_info.discription|safe}} </p>
							</div>
						</div>
					</div>

					<div class="colophon">
						<p>{{footer_info.discription|safe}}</p>
					</div>
				</div>
			</footer>
		</div>
		

		

		<script src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en"></script>
		<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
		<script src="{% static 'js/plugins.js' %}"></script>
		<script src="{% static 'js/app.js' %}"></script>
		
	</body>

</html>

templates/email.html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <H6>Hello <b>Admin</b></H6><br>
        <p>{{message}}</p><br>
        <p>Thanks & Regards</p><br>
        <H6>{{name}}</H6><br>
        <H6>{{phone_number}}</H6><br>
        <H6>{{address}}</H6><br>
    </body>
</html>

templates/gallery.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
		
		<title>Beauty Salon | Gallery</title>
		<!-- Loading third party fonts -->
		<link href="{% static 'fonts/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
		<link href="{% static 'fonts/novecento-font/novecento-font.css' %}" rel="stylesheet" type="text/css">
		<!-- Loading main css file -->
		<link rel="stylesheet" href="{% static 'style.css' %}">
		
		<!--[if lt IE 9]>
		<script src="js/ie-support/html5.js"></script>
		<script src="js/ie-support/respond.js"></script>
		<![endif]-->

	</head>


	<body>

		<div id="site-content">
			
			<header class="site-header">
				<div class="container">
					<a id="branding" href="{% url 'home' %}">
						{% if company_info.logo %}
							<img src={{company_info.logo.url}} alt="Company name" class="logo" height="50" width="50">
						{% else %}
							<img src="{% static 'images/logo.png' %}" alt="Company name" class="logo">
						{% endif %}
						<div class="logo-copy">
							<h1 class="site-title">{{company_info.company_name}}</h1>
							<small class="site-description">{{company_info.slogan}}</small>
						</div>
					</a> <!-- #branding -->

					
					<!-- Default snippet for navigation -->
					<div class="main-navigation">
						<button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
						<ul class="menu">
							<li class="menu-item"><a href="{% url 'home' %}">Home</a></li>
							<li class="menu-item"><a href="{% url 'about' %}">About</a></li>
							<li class="menu-item"><a href="{% url 'service' %}">Services</a></li>
							<li class="menu-item current-menu-item"><a href="{% url 'gallery' %}">Gallery</a></li>
							<li class="menu-item"><a href="{% url 'contact-us' %}">Contact</a></li>
						</ul> <!-- .menu -->
					</div> <!-- .main-navigation -->

					<div class="mobile-navigation"></div>
				</div>
			</header>

			<main class="main-content">
				<div class="page">
					<div class="container">
						<div class="text-center">
							<div class="filter-links filterable-nav">
								<select class="mobile-filter">
									<option value="*">Show all</option>
									{% for category in category_list %}
										<option value=".{{category.name}}">{{category.name}}</option>
									{% endfor %}
									<option value=".manicure">manicure</option>
									<option value=".pedicure">pedicure</option>
									<option value=".face">face</option>
									<option value=".makeup">makeup</option>
								</select>
								<a href="#" class="current wow fadeInRight" data-filter="*">Show all</a>
								{% for category in category_list %}
									<a href="#" class="wow fadeInRight" data-wow-delay=".2s" data-filter=".{{category.name}}">{{category.name}}</a>
								{% endfor %}
							</div>
						</div>

						<div class="filterable-items">
							{% for gallery in gallery_list %}
								<div class="gallery-item filterable-item {{gallery.category.name}}">
									<a href="{{gallery.image.url}}">
										<figure class="featured-image">
											<img src="{{gallery.image.url}}" alt="">
											<figcaption>
												<h2 class="gallery-title">{{gallery.topic}}</h2>
												<p>{{gallery.discription|safe}}</p>
											</figcaption>
										</figure>
									</a>
								</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</main>

			<footer class="site-footer">
				<div class="container">
					<div class="row">
						<div class="col-md-3">
							<div class="widget contact-widget">
								<h3 class="widget-title">Contact</h3>
								<div class="contact-info">
									<address>
										<img src="{% static 'images/icon-map-small.png' %}" class="icon">
										<p><strong>{{company_info.company_name}}</strong>{{company_info.address}}</p>
									</address>
									<a href="mailto:{{company_info.email}}" class="mail"><img src="{% static 'images/icon-envelope-small.png' %}" class="icon">{{company_info.email}}</a>
									<a href="tel:{{company_info.phone_number}}" class="phone"><img src="{% static 'images/icon-phone-small.png' %}" class="icon">{{company_info.phone_number}}</a>
								</div>
							</div>
						</div>
						<div class="col-md-3">
							<div class="widget">
								<h3 class="widget-title">Social Media</h3>
								<div class="social-links">
									<a href={{company_info.fb}} target="_blank"><i class="fa fa-facebook"></i></a>
									<a href={{company_info.twitter}} target="_blank"><i class="fa fa-twitter"></i></a>
									<a href={{company_info.google}} target="_blank"><i class="fa fa-google-plus"></i></a>
									<a href={{company_info.pinterest}} target="_blank"><i class="fa fa-pinterest"></i></a>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="widget">
								<h3 class="widget-title">Newsletter</h3>
								<p>{{company_info.discription|safe}} </p>
							</div>
						</div>
					</div>

					<div class="colophon">
						<p>{{footer_info.discription|safe}}</p>
					</div>
				</div>
			</footer>
		</div>
		

		

		<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
		<script src="{% static 'js/plugins.js' %}"></script>
		<script src="{% static 'js/app.js' %}"></script>
		
	</body>

</html>

templates/index.html
{% load static %}
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
		
		<title>Beauty Salon</title>
		<!-- Loading third party fonts -->
		<link href="{% static 'fonts/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
		<link href="{% static 'fonts/novecento-font/novecento-font.css' %}" rel="stylesheet" type="text/css">
		<!-- Loading main css file -->
		<link rel="stylesheet" href="{% static 'style.css' %}">
		
		<!--[if lt IE 9]>
		<script src="js/ie-support/html5.js"></script>
		<script src="js/ie-support/respond.js"></script>
		<![endif]-->

	</head>


	<body class="homepage header-collapse">

		<div id="site-content">
			
			<header class="site-header">
				<div class="container">
					<a id="branding" href="{% url 'home' %}">
						{% if company_info.logo %}
							<img src={{company_info.logo.url}} alt="Company name" class="logo" height="50" width="50">
						{% else %}
							<img src="{% static 'images/logo.png' %}" alt="Company name" class="logo">
						{% endif %}
						<div class="logo-copy">
							<h1 class="site-title">{{company_info.company_name}}</h1>
							<small class="site-description">{{company_info.slogan}}</small>
						</div>
					</a> <!-- #branding -->

					
					<!-- Default snippet for navigation -->
					<div class="main-navigation">
						<button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
						<ul class="menu">
							<li class="menu-item current-menu-item"><a href="{% url 'home' %}">Home</a></li>
							<li class="menu-item"><a href="{% url 'about' %}">About</a></li>
							<li class="menu-item"><a href="{% url 'service' %}">Services</a></li>
							<li class="menu-item"><a href="{% url 'gallery' %}">Gallery</a></li>
							<li class="menu-item"><a href="{% url 'contact-us' %}">Contact</a></li>
						</ul> <!-- .menu -->
					</div> <!-- .main-navigation -->

					<div class="mobile-navigation"></div>
				</div>
			</header>
			
			<div class="hero hero-slider">
				<ul class="slides">
					{% for obj in slider_list %}
					<li data-bg-image={{obj.image.url}}>
						<div class="container">
							<h3 class="slider-subtitle">{{obj.topic}}</h3>
							<h2 class="slider-title">{{obj.sub_topic}}</h2>
							<p>{{obj.discription|safe}}</p>
							<a href="#" class="button large">Read more</a>
						</div>
					</li>
					{% endfor %}
				</ul>
			</div>

			<main class="main-content">
				<div class="fullwidth-block features-section">
					<div class="container">
						<h2 class="section-title">our Services</h2>
						<div class="row">
							{% for service in service_list %}
								<div class="col-md-3">
									<div class="feature">
										<img src="{{ service.image.url }}" class="feature-image">
										<h2 class="price"><b>Rs{{service.price}}</b></h2>
										<h3 class="feature-title">{{ service.topic }}</h3>
										<p>{{ service.discription|safe}}</p>
									</div>
								</div>
							{% endfor %}
						</div> <!-- .row -->
					</div> <!-- .container -->
				</div> <!-- .fullwidth-block.features-section -->

				<div class="fullwidth-block information-section">
					<div class="container">
						<h2 class="section-title">Information</h2>
						<div class="row">
							<div class="col-md-4">
								<figure><img src="{{aboutus.image.url}}" ></figure>
							</div>
							<div class="col-md-4">
								<p>{{aboutus.discription|safe}}</p>
							</div>
							<div class="col-md-4">
								<p>{{aboutus.discription2|safe}}</p>
							</div>
						</div>
					</div>
				</div> <!-- .fullwidth-block.information-section -->
			</main>

			<footer class="site-footer">
				<div class="container">
					<div class="row">
						<div class="col-md-3">
							<div class="widget contact-widget">
								<h3 class="widget-title">Contact</h3>
								<div class="contact-info">
									<address>
										<img src="{% static 'images/icon-map-small.png' %}" class="icon">
										<p><strong>{{company_info.company_name}}</strong>{{company_info.address}}</p>
									</address>
									<a href="mailto:{{company_info.email}}" class="mail"><img src="{% static 'images/icon-envelope-small.png' %}" class="icon">{{company_info.email}}</a>
									<a href="tel:{{company_info.phone_number}}" class="phone"><img src="{% static 'images/icon-phone-small.png' %}" class="icon">{{company_info.phone_number}}</a>
								</div>
							</div>
						</div>
						<div class="col-md-3">
							<div class="widget">
								<h3 class="widget-title">Social Media</h3>
								<div class="social-links">
									<a href={{company_info.fb}} target="_blank"><i class="fa fa-facebook"></i></a>
									<a href={{company_info.twitter}} target="_blank"><i class="fa fa-twitter"></i></a>
									<a href={{company_info.google}} target="_blank"><i class="fa fa-google-plus"></i></a>
									<a href={{company_info.pinterest}} target="_blank"><i class="fa fa-pinterest"></i></a>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="widget">
								<h3 class="widget-title">Newsletter</h3>
								<p>{{company_info.discription|safe}} </p>
							</div>
						</div>
					</div>

					<div class="colophon">
						<p>{{footer_info.discription|safe}}</p>
					</div>
				</div>
			</footer>
		</div>
		

		

		<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
		<script src="{% static 'js/plugins.js' %}"></script>
		<script src="{% static 'js/app.js' %}"></script>
		
	</body>

</html>